# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Coding for Life Sciences
subtitle: 从数据，模型中获取生物知识
description: 关注从数据和模型中获取生物知识的博客
keywords: Biology, Data Science,AI,Informatics,Modeling;
author: Longteng Wang
language: zh-cn
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://landau1994.github.io
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:
  - README.md

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0s
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: false
  line_number: false
  auto_detect: false
  tab_replace: false
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date
  
# Category & Tag
default_category: genomics
defatul_tag: genomics
category_map:
   基因组学: genomics
   编程实践: implementation
   文献阅读: reference
   数学学习: math
   其他: others
tag_map:
   学习笔记: note
   biostat: biostat
   machine learning: machine learning
   Stochastic Process: stochastic Process
   Probability: Probability
   Modeling: Modeling
   Graph: Graph
   Causal Inference: Causal Inference
   Bayesian: Bayesian
   biology: biology
   genomics: genomics
   genetics: genetics
   cell biology: cell biology
   immunology: immunology
   RNA-seq: RNA-seq
   DNA microarray: DNA microarray
   scRNA-seq: scRNA-seq
   single cell sequencing: sc-seq
   sequencing: sequencing
   ChIP-seq: ChIP-seq
   ATAC-seq: ATAC-seq
   HiC: HiC
   ENCODE: ENCODE
   NGS: NGS
   biotech: biotech 
   R: R
   Python: Python
   Shell: Shell
   hexo: hexo
   NodeJS: NodeJS

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page



# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/



theme: jsimple

# Local search
search:
  path: search.json
  field: all
  content: true

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: git@github.com:Landau1994/landau1994.github.io.git
  branch: master
  message: 
